services:
  redis-master:
    image: "redis/redis-stack:latest"
    container_name: redis-master
    volumes:
      - ./master.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
      - ./create-index.sh:/create-index.sh
    command: > 
      bash -c "bash /create-index.sh & redis-stack-server /usr/local/etc/redis/redis.conf"
    user: root
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      redis_network:
        ipv4_address: 172.40.0.10
    restart: always
    

  redis-replica1:
    image: "redis/redis-stack:latest"
    container_name: redis-replica1
    volumes:
      - ./replica.conf:/usr/local/etc/redis/redis.conf
      - ./create-index.sh:/create-index.sh
    command: > 
      bash -c "bash /create-index.sh & redis-stack-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
      - "8002:8001"
    networks:
      redis_network:
        ipv4_address: 172.40.0.11
    restart: always

  redis-replica2:
    image: "redis/redis-stack:latest"
    container_name: redis-replica2
    volumes:
      - ./replica.conf:/usr/local/etc/redis/redis.conf
      - ./create-index.sh:/create-index.sh
    command: > 
      bash -c "bash /create-index.sh & redis-stack-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - redis-master
    ports:
      - "6381:6379"
      - "8003:8001"

    networks:
      redis_network:
        ipv4_address: 172.40.0.12
    restart: always
  
  redis-replica3:
    image: "redis/redis-stack:latest"
    container_name: redis-replica3
    volumes:
      - ./replica.conf:/usr/local/etc/redis/redis.conf
      - ./create-index.sh:/create-index.sh
    command: > 
      bash -c "bash /create-index.sh & redis-stack-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - redis-master
    ports:
      - "6382:6379"
      - "8004:8001"
      
    networks:
      redis_network:
        ipv4_address: 172.40.0.13
    restart: always

  grafana: 
    container_name: monitoring
    image: grafana/grafana:latest
    ports: 
      - 3000:3000
    networks:
      redis_network:
        ipv4_address: 172.40.0.60
    restart: always

networks:
  redis_network:
      driver: bridge
      ipam:
          config:
              - subnet: 172.40.0.0/16
                gateway: 172.40.0.1
